### ISSUE TITLE
star topology switchvm.network should be switch.vm.network

### ISSUE THREAD

**Issue by larraunanue** [nlacko97/automated-vagrant-network-deployment#2]
![image](https://user-images.githubusercontent.com/45813867/150805979-529151cb-6b8a-4cd3-b55d-f7cb8e7a5194.png)

![image](https://user-images.githubusercontent.com/45813867/150806107-824f3a45-083f-4bd2-8fbb-2d88fba96e18.png)

It seams that the template doesn't add a point. Even if in theory that I see that in the template is with a ".".

Could someone check if it works for you? The test has been with 2 host

**Comment by BSSB33** [comment]
Fix Commited

**Comment by BSSB33** [comment]
Fix Pushed
