### ISSUE TITLE
network devices name to be updated

### ISSUE THREAD

**Issue by larraunanue** [nlacko97/automated-vagrant-network-deployment#3]
Hello, I saw that if we assign e.g 3 devices. for each host, the enp0sN is being updated automatically. e.g host-a enp0s8. host-b enp0s9 and host-c enp0s10.  

But like that, the VM starts but without having the link enp0s10. Here you have a screenshot of host-c. (And the same happens with host-b)

![image](https://user-images.githubusercontent.com/45813867/150816452-9d90906f-e2f5-4e76-bce3-06e2211e77b2.png)

The template needs to be updated so that the first interface for each VM starts being enp0s8. Not updating it gradually.

**Comment by larraunanue** [comment]
FYI, in my case, if I add a 4th host. The new interface generated in the switch for host-d it's not called enp0s11 but **enps16** . Therefore this would need also to be changed in the template. 
![image](https://user-images.githubusercontent.com/45813867/150823287-e0b9878b-c7f4-42ec-b5e0-76cf4ab0beb2.png)


According to this post https://github.com/GNS3/gns3-gui/issues/2299

This is the other. So it needs to be taken account for the template. This is according of previous msg, suggesting to use enp0s8 as the first internal network interface for all the VMs
![image](https://user-images.githubusercontent.com/45813867/150823368-274355be-3766-4bc3-9069-c77fddd28fa5.png)

**Comment by BSSB33** [comment]
Notice: The generation is from number 8 already

**Comment by nlacko97** [comment]
The current version runs correctly for the star topology, generating the inet numbers as in the suggestion.
