### ISSUE TITLE
Vagrantfile_template nics, needs to be automatized

### ISSUE THREAD

**Issue by larraunanue** [nlacko97/automated-vagrant-network-deployment#4]
Hi all,

This should be also automatized.
![image](https://user-images.githubusercontent.com/45813867/150824507-7ab74550-9937-4ce6-933c-e1cac7541147.png)

The max interfaces in a network card seem to be 8.  Therefore for our use case. enp0s3 + 7 more. That would allow us, in the Star topology for instance. To connect MAX 7 host to the switch, as the switch would have 7 interfaces left for the internal networks. Therefore   **vb.customize ["modifyvm", :id, "--nicpromisc5", "allow-all"]**  should be automatically updated. In this case as the last one is **nicpromisc5**, would allow us to have 4 hosts connected to the switch. In case there where just 3, the last one should be nicpromisc4 (remember that enp0s3 is used for NAT). whereas if we would like to connect 7 hosts, the last should be nicpromisc8

**Comment by BSSB33** [comment]
Commint d180232de03cf27fe6c135d00447ea66836cc225 fixes the issue and automatizes this part of the script generation.
